services:
  db:
    image: postgres:17
    container_name: TA_mov-db
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      -  TA_internal

  app:
    build: .
    container_name: TA-mov-app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - TA_internal
      - TA_tunn_net
      - TA-IW_NET

networks:
  TA_internal:
  TA_tunn_net:
    external: true
  TA-IW_NET:
    external: true
