services:
  db:
    image: postgres:17
    container_name: TA-mov-db
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA_PATH}:/var/lib/postgresql/data
    networks:
      -  TA_internal

  app:
    build: .
    container_name: TA-mov-app
    env_file:
      - .env
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - TA_internal
      - cloudflared_net

networks:
  TA_internal:
  cloudflared_net:
    external: true
